Undefine CALLBACK after including Shlwapi.h
clang/Analysis/CFG.h uses CALLBACK as a template parameter to the
function VisitBlockStmts. Since this is defined as a calling convention
in minwindef.h, we end up with an error similar to the following:

CFG.h(1380): error C2988: unrecognizable template declaration/definition

The fix is a continuation of the existing workaround to just undefine
the offending macro since it's not needed in our code anyway.